# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "opensuse/Leap-15.3.x86_64"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |n|
    config.vm.define "k3s-server-#{n}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "k3s-server-#{n}"
      subconfig.vm.network "private_network", ip: "192.168.56.#{10 + n}"
      subconfig.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
      end

      subconfig.ssh.username = 'root'
      subconfig.ssh.password = 'vagrant'
      subconfig.ssh.insert_key = 'true'
      # ssh -i .vagrant/machines/default/virtualbox/private_key -p 2222 root@192.168.56.#{10 + n}
      #config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/root/.ssh/id_ed25519.pub"

      # subconfig.vm.provision "shell", inline: <<-SHELL
      #   zypper update -y    # <---- needs a reboot !!!!!!!!!!!!!
      #   zypper --non-interactive install \
      #     curl \
      #     command-not-found \
      #     vim \
      #     netcat-openbsd \
      #     hostname \
      #     bind-utils
      # SHELL

      # execute code before reload using reload-plugin
      # vagrant plugin install vagrant-reload
      subconfig.vm.provision "shell", inline: <<-SHELL
        zypper update -y    # <---- needs a reboot !!!!!!!!!!!!!
      SHELL

      # trigger reload
      subconfig.vm.provision :reload

      # execute code after reload
      subconfig.vm.provision "shell", inline: <<-SHELL
        zypper --non-interactive install \
          curl \
          command-not-found \
          vim \
          netcat-openbsd \
          hostname \
          bind-utils
      SHELL
    end
  end

end
