# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "opensuse/Leap-15.3.x86_64"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |n|
    config.vm.define "k3s-server-#{n}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "k3s-server-#{n}"
      subconfig.vm.network "private_network", ip: "192.168.56.#{10 + n}"
      subconfig.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
      end

      subconfig.vm.provision "shell", inline: <<-SHELL
        zypper update
        zypper --non-interactive install curl command-not-found vim netcat-openbsd hostname

        IP=$(ip -4 addr show eth1 | grep -oP "(?<=inet ).*(?=/)")
        echo "======== K3S_NODE_NAME=\"$(hostname)\" INSTALL_K3S_EXEC=\"--node-external-ip $IP --node-ip $IP\""
        #curl -sfL https://get.k3s.io | K3S_NODE_NAME="$(hostname)" INSTALL_K3S_EXEC="--node-external-ip $IP --node-ip $IP" sh -
      SHELL
    end
  end

end
